import Container from "@components/Container";
import { Heading1 } from "@components/Typography";
import Basic from "@layouts/Basic";
import Head from "next/head";
import About from "./Home/About";
import Banner from "./Home/Banner";
import Experience from "./Home/Experience";
import GetInTouch from "./Home/GetInTouch";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Razorpay Resume - Varun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Basic>
        <main>
          <Banner />
          <About />
          <Experience />
          <GetInTouch />
        </main>
      </Basic>
    </div>
  );
}
